### ISSUE TITLE
Agent triggers

### ISSUE THREAD

**Issue by gabehamilton** [nearai/nearai#672]
A triggering event can be specified in agent metadata.

```
agent:
  trigger:
    event_source: 'flatirons.near/twitter_mentions'
    event_name: 'mention'
    event_data: ['@NearSecretAgent', '@ilblackdragon']
```

When an agent is saved with trigger metadata the trigger is added to the event source's trigger list.
When an event occurs, triggers are checked, and matching agents are run.

.
description updated: to have list of accounts per comment below.

**Comment by zavodil** [comment]
My sugestion:
```
agent:
  trigger:
    event_name: 'twitter_mention'
    event_data: ['NearAgent1', 'NearSecretAgent2']
```
